sudo: required
dist: bionic
language: cpp
arch:
    - amd64
    - arm64

compiler:
    - gcc

install:
    - sudo apt-get update -y
    - sudo apt-get install -y build-essential automake1.11 autoconf libevent-dev libseccomp-dev git tar libio-socket-ssl-perl libssl-dev openssl

script:
    - ./autogen.sh
    - ./configure --enable-seccomp --enable-tls
    - make -j
    - make test
    - make test_tls
